-- 1. Users Table
CREATE TABLE IF NOT EXISTS Users (
    UserID SERIAL PRIMARY KEY,
    Name VARCHAR(100) NOT NULL,
    Email VARCHAR(100) UNIQUE NOT NULL,
    Password VARCHAR(200) NOT NULL,
    Role VARCHAR(20) DEFAULT 'user',
    Contact VARCHAR(20) NOT NULL,
    Location VARCHAR(200) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 2. Hospitals Table
CREATE TABLE IF NOT EXISTS Hospitals (
    HospitalID SERIAL PRIMARY KEY,
    Name VARCHAR(200) NOT NULL,
    Location VARCHAR(200) NOT NULL,
    Contact VARCHAR(20) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 3. Donors Table
CREATE TABLE IF NOT EXISTS Donors (
    DonorID SERIAL PRIMARY KEY,
    UserID INT REFERENCES Users(UserID) ON DELETE CASCADE,
    BloodGroup VARCHAR(5) NOT NULL,
    Age INT NOT NULL,
    Gender VARCHAR(10) NOT NULL,
    Verified BOOLEAN DEFAULT FALSE,
    IsAvailable BOOLEAN DEFAULT TRUE,
    LastDonationDate DATE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 4. Recipients Table
CREATE TABLE IF NOT EXISTS Recipients (
    RecipientID SERIAL PRIMARY KEY,
    UserID INT REFERENCES Users(UserID) ON DELETE CASCADE,
    BloodGroup VARCHAR(5) NOT NULL,
    Contact VARCHAR(20) NOT NULL,
    Location VARCHAR(200) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 5. Availability Table
--CREATE TABLE IF NOT EXISTS Availability (
--    AvailID SERIAL PRIMARY KEY,
--    DonorID INT REFERENCES Donors(DonorID) ON DELETE CASCADE,
--    Status VARCHAR(20) NOT NULL,
--    LastUpdated TIMESTAMP NOT NULL,
--    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
--);

-- 6. Requests Table
CREATE TABLE IF NOT EXISTS Requests (
    RequestID SERIAL PRIMARY KEY,
    RecipientID INT REFERENCES Recipients(RecipientID) ON DELETE CASCADE,
    BloodGroup VARCHAR(5) NOT NULL,
    UrgencyLevel VARCHAR(20) NOT NULL,
    Status VARCHAR(20) DEFAULT 'Pending',
    RequestDate TIMESTAMP NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 7. Matched_Donor Table
CREATE TABLE IF NOT EXISTS Matched_Donor (
    MatchID SERIAL PRIMARY KEY,
    RequestID INT REFERENCES Requests(RequestID) ON DELETE CASCADE,
    DonorID INT REFERENCES Donors(DonorID) ON DELETE CASCADE,
    MatchDate TIMESTAMP NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 8. Verification Table
CREATE TABLE IF NOT EXISTS Verification (
    VerifyID SERIAL PRIMARY KEY,
    HospitalID INT REFERENCES Hospitals(HospitalID) ON DELETE CASCADE,
    DonorID INT REFERENCES Donors(DonorID) ON DELETE CASCADE,
    VerifiedOn TIMESTAMP NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);